In [4]:
from . import io

ImportError: attempted relative import with no known parent package

In [7]:
import ome_zarr_neuro.io

[{'scale': [1, 0.004, 0.0018, 0.0018], 'type': 'scale'}]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[-0.0018  0.      0.      0.    ]
 [ 0.     -0.0018  0.      0.    ]
 [ 0.      0.     -0.004   0.    ]
 [ 0.      0.      0.      1.    ]]
[{'scale': [1, 0.004, 0.0018, 0.0018], 'type': 'scale'}]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[-0.0018  0.      0.      0.    ]
 [ 0.     -0.0018  0.      0.    ]
 [ 0.      0.     -0.004   0.    ]
 [ 0.      0.      0.      1.    ]]
ras2vox
TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[  -0.        ,   -0.        , -250.        ,   -0.        ],
       [  -0.        , -555.55555556,   -0.        ,   -0.        ],
       [-555.55555556,   -0.        ,   -0.        ,   -0.        ],
       [   0.        ,    0.        ,    0.        ,    1.        ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None)
DaskImage(darr=dask.array<getitem, shape=(1, 2212, 11732, 7439), dtype=uint16, chunks

In [10]:
import dask.array as da
from transform import DaskImage
import numpy as np

# function to extract ome zarr subvolume around nifti label from e.g. downsampled nii
in_zarr = '/cifs/prado/Kate/AK_Pipeline_LSM/spimprep/bids/sub-o28/micr/sub-o28_sample-brain_acq-prestitched_SPIM.ome.zarr/'
tiny_zarr='/local/SPIMquant/test_out/results/sub-o28/micr/sub-o28_sample-brain_acq-prestitched_desc-tiny_SPIM.ome.zarr'
in_lbl_nii='/local/SPIMquant/test_out/results/sub-o28/micr/sub-o28_sample-brain_acq-prestitched_from-ABAv3_level-5_desc-deform_dseg.nii.gz'

def extract_subvol_ome_zarr():
    zarr_img = DaskImage.from_path(in_zarr) 
    nii_label = DaskImage.from_path(in_lbl_nii)
    print('ras2vox')
    print(zarr_img.ras2vox) 
    print(zarr_img)
    print(nii_label.darr.shape)

    darr_label = da.zeros_like(nii_label.darr)
    darr_label[nii_label.darr==457] = 1

    indices = da.argwhere(darr_label).compute()
    # Compute the minimum and maximum extents in each dimension
    min_extent = indices.min(axis=0)
    max_extent = indices.max(axis=0)


    #NEED TO INTERPOLATE EXTENTS FROM VOX (DS LEVEL) -> RAS (PHYS)-> VOX (FULL RES)
    
    #get bounds
    print(min_extent)
    print(max_extent)

    zarr_img.darr = zarr_img.darr[min_extent[0]:max_extent[0]+1, 
                            min_extent[1]:max_extent[1]+1, 
                        min_extent[2]:max_extent[2]+1,
                        min_extent[3]:max_extent[3]+1,]
    print(zarr_img.darr.shape)
    zarr_img.to_ome_zarr('test_subvol.ome.zarr')


In [11]:
extract_subvol_ome_zarr()

[{'scale': [1, 0.004, 0.0018, 0.0018], 'type': 'scale'}]
vox2ras after reading zarr
[[-0.004   0.      0.      0.    ]
 [ 0.     -0.0018  0.      0.    ]
 [ 0.      0.     -0.0018  0.    ]
 [ 0.      0.      0.      1.    ]]
[{'scale': [1, 0.004, 0.0018, 0.0018], 'type': 'scale'}]
vox2ras after reading zarr
[[-0.004   0.      0.      0.    ]
 [ 0.     -0.0018  0.      0.    ]
 [ 0.      0.     -0.0018  0.    ]
 [ 0.      0.      0.      1.    ]]
ras2vox
TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[-250.        ,   -0.        ,   -0.        ,   -0.        ],
       [  -0.        , -555.55555556,   -0.        ,   -0.        ],
       [  -0.        ,   -0.        , -555.55555556,   -0.        ],
       [   0.        ,    0.        ,    0.        ,    1.        ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None)
DaskImage(darr=dask.array<getitem, shape=(1, 2212, 11732, 7439), dtype=uint16, chunksize=(1, 1, 4096, 4096), chunktype=numpy.ndarray>, ras2vox=TransformS

In [7]:
zarr_img = DaskImage.from_path(in_zarr) 
zarr_img.vox2ras @ np.array([0,0,0,1]).reshape((4,1))

[{'scale': [1, 0.004, 0.0018, 0.0018], 'type': 'scale'}]
vox2ras after reading zarr
[[-0.004   0.      0.      0.    ]
 [ 0.     -0.0018  0.      0.    ]
 [ 0.      0.     -0.0018  0.    ]
 [ 0.      0.      0.      1.    ]]
[{'scale': [1, 0.004, 0.0018, 0.0018], 'type': 'scale'}]
vox2ras after reading zarr
[[-0.004   0.      0.      0.    ]
 [ 0.     -0.0018  0.      0.    ]
 [ 0.      0.     -0.0018  0.    ]
 [ 0.      0.      0.      1.    ]]


ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [28]:
zarr_img.vox2ras.affine @ np.array([1,1,1,1])

array([-0.0018, -0.0018, -0.004 ,  1.    ])

In [29]:
zarr_img

DaskImage(darr=dask.array<getitem, shape=(1, 2212, 11732, 7439), dtype=uint16, chunksize=(1, 1, 4096, 4096), chunktype=numpy.ndarray>, ras2vox=TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[  -0.        ,   -0.        , -250.        ,   -0.        ],
       [  -0.        , -555.55555556,   -0.        ,   -0.        ],
       [-555.55555556,   -0.        ,   -0.        ,   -0.        ],
       [   0.        ,    0.        ,    0.        ,    1.        ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None), vox2ras=TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[ 0.    ,  0.    , -0.0018,  0.    ],
       [ 0.    , -0.0018,  0.    ,  0.    ],
       [-0.004 ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None), axes_nifti=False)

In [30]:
label_img

NameError: name 'label_img' is not defined

In [32]:
in_lbl_nii='/local/SPIMquant/test_out/results/sub-o28/micr/sub-o28_sample-brain_acq-prestitched_from-ABAv3_level-5_desc-deform_dseg.nii.gz'

daskimg_from_nii = DaskImage.from_path(in_lbl_nii)

In [34]:
daskimg_from_nii.to_ome_zarr('from_nii.ome.zarr')

[-0.0576 -0.0576 -0.032 ]
writing full-res image to zarr single threaded
[########################################] | 100% Completed | 202.37 ms
writing downsampled images to zarr
[########################################] | 100% Completed | 1.01 sms


In [35]:
daskimg_from_zarr_from_nii = DaskImage.from_path('from_nii.ome.zarr')

[{'scale': [1, -0.03200000151991844, -0.0575999990105629, -0.0575999990105629], 'type': 'scale'}]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[0.0576 0.     0.     0.    ]
 [0.     0.0576 0.     0.    ]
 [0.     0.     0.032  0.    ]
 [0.     0.     0.     1.    ]]
[{'scale': [1, -0.03200000151991844, -0.0575999990105629, -0.0575999990105629], 'type': 'scale'}]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
[[0.0576 0.     0.     0.    ]
 [0.     0.0576 0.     0.    ]
 [0.     0.     0.032  0.    ]
 [0.     0.     0.     1.    ]]


In [36]:
daskimg_from_zarr_from_nii

DaskImage(darr=dask.array<getitem, shape=(1, 277, 366, 232), dtype=float64, chunksize=(1, 277, 196, 232), chunktype=numpy.ndarray>, ras2vox=TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[ 0.        ,  0.        , 31.24999852,  0.        ],
       [ 0.        , 17.36111141,  0.        ,  0.        ],
       [17.36111141,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None), vox2ras=TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[0.    , 0.    , 0.0576, 0.    ],
       [0.    , 0.0576, 0.    , 0.    ],
       [0.032 , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 1.    ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None), axes_nifti=False)

In [37]:
daskimg_from_nii

DaskImage(darr=dask.array<array, shape=(1, 232, 366, 277), dtype=float64, chunksize=(1, 232, 268, 268), chunktype=numpy.ndarray>, ras2vox=TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[-17.36111141,  -0.        ,  -0.        ,  -0.        ],
       [ -0.        , -17.36111141,  -0.        ,  -0.        ],
       [ -0.        ,  -0.        , -31.24999852,  -0.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None), vox2ras=TransformSpec(tfm_type=<TransformType.AFFINE_RAS: 1>, affine=array([[-0.0576,  0.    ,  0.    , -0.    ],
       [ 0.    , -0.0576,  0.    , -0.    ],
       [ 0.    ,  0.    , -0.032 ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]]), disp_xyz=None, disp_grid=None, disp_ras2vox=None), axes_nifti=True)

In [38]:
daskimg_from_zarr_from_nii.to_nifti('from_zarr_from_nii.nii')

In [39]:
import nibabel as nib
nib_to_zarr_and_back = nib.load('from_zarr_from_nii.nii')
nib_to_zarr_and_back.affine

array([[0.    , 0.    , 0.0576, 0.    ],
       [0.    , 0.0576, 0.    , 0.    ],
       [0.032 , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 1.    ]])

In [42]:
nib_orig = nib.load(in_lbl_nii)
nib_orig.affine

array([[-0.0576,  0.    ,  0.    , -0.    ],
       [ 0.    , -0.0576,  0.    , -0.    ],
       [ 0.    ,  0.    , -0.032 ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [44]:
daskimg_from_nii.to_nifti('from_nii.nii')

In [45]:
nib_from_nii_to_dimg_to_nii = nib.load('from_nii.nii')
nib_from_nii_to_dimg_to_nii.affine

array([[-0.0576,  0.    ,  0.    , -0.    ],
       [ 0.    , -0.0576,  0.    , -0.    ],
       [ 0.    ,  0.    , -0.032 ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [47]:
from pathlib import Path

p = Path('test.nii')
p.suffixes

['.nii']